language: go

go:
  - 1.6.4
  - 1.7.5
  - 1.8rc3

# first part of the GOARCH workaround
# setting the GOARCH directly doesn't work, since the value will be overwritten later
# so set it to a temporary environment variable first
env:
  - TRAVIS_GOARCH=amd64
  - TRAVIS_GOARCH=386

# second part of the GOARCH workaround
# now actually set the GOARCH env variable to the value of the temporary variable set earlier
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - export GOARCH=$TRAVIS_GOARCH
  - go env # for debugging

script:
  - go get -t ./...
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --progress
